default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: bogdanchil

development:
  <<: *default
  database: fullstack_dev

test:
  <<: *default
  database: fullstack_test

production:
  <<: *default
  database: fullstack_production
